name: Bot Detalle (Lunes a Viernes)

on:
  schedule:
    # Ejecutar a las 21:00 UTC (18:00 Argentina - Cierre)
    - cron: '0 21 * * 1-5'
  workflow_dispatch: # Botón manual

jobs:
  run_detalle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Instalar Dependencias (Configuración Estable)
        run: |
          pip install "numpy<2.0.0"
          pip install pandas==1.3.5
          pip install yfinance requests lxml

      # --- EJECUCIÓN DEL BOT DETALLADO ---
      - name: Correr Bot Detalle
        env:
          # Usamos el Token general
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          # ¡OJO AQUÍ! Usamos el ID del NUEVO grupo
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID_DETALLE }}
        run: python bot_detalle.py
