name: Bot Acciones (Lunes a Viernes)

on:
  schedule:
    # Horarios UTC (Aprox: Apertura, Medio d√≠a, Cierre NY)
    - cron: '30 14 * * 1-5'
    - cron: '0 17 * * 1-5'
    - cron: '0 20 * * 1-5'
  workflow_dispatch:

jobs:
  run_stocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Instalar Dependencias
        run: |
          pip install "numpy<2.0.0"
          pip install pandas==1.3.5
          pip install yfinance requests

      # --- BOT 1: Alerta Simple ---
      - name: Correr Alerta Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python alerta_bot.py

      # --- BOT 2: Multi-Timeframe ---
      - name: Correr MTF Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python mtf_bot.py

      # 1. Ejecutamos el Nuevo Maestro de Acciones (El que acabamos de hacer)
      - name: Correr Bot Maestro Acciones
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot_maestro.py
